# Generated by Django 5.0.6 on 2024-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0003_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='bancoCUP',
            field=models.CharField(max_length=200, null=True, verbose_name='Banco CUP'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cuentaCL',
            field=models.CharField(max_length=50, null=True, verbose_name='Cuenta CL'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cuentaCUP',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta CUP'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cuentaEst',
            field=models.CharField(max_length=50, null=True, verbose_name='Cuenta Estandarizada'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='direccion',
            field=models.CharField(max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='margen',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Margen CL'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(max_length=200, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='titularCL',
            field=models.CharField(max_length=200, null=True, verbose_name='Titular Cuenta CL'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='titularCUP',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titular Cuenta CUP'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='vigencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vigencia de Oferta'),
        ),
    ]
