# Generated by Django 5.0.6 on 2024-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Categoría')),
                ('habilitada', models.BooleanField(default=True, verbose_name='Categoría Activada/Categoría no Activada')),
                ('margporc', models.BooleanField(verbose_name='Margen/Porciento')),
                ('valormag', models.FloatField()),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('reuup', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('Telefono', models.CharField(max_length=50)),
                ('Provincia', models.CharField(max_length=80)),
                ('Abreviatura', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Entidad')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('cuentaCUP', models.CharField(blank=True, max_length=50, null=True)),
                ('cuentaCL', models.CharField(blank=True, max_length=50, null=True)),
                ('titularCUP', models.CharField(blank=True, max_length=200, null=True)),
                ('titularCL', models.CharField(blank=True, max_length=200, null=True)),
                ('bancoCUP', models.CharField(blank=True, max_length=200, null=True)),
                ('cuentaEst', models.CharField(blank=True, max_length=50, null=True)),
                ('vigencia', models.IntegerField(null=True)),
                ('margen', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
