# Generated by Django 5.0.6 on 2024-05-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Abreviatura',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='reuup',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='valormag',
            field=models.FloatField(verbose_name='Valor del Margen Comercial CUP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Provincia',
            field=models.CharField(choices=[('OCC', 'Occidente'), ('CEN', 'Centro'), ('ORI', 'Oriente')], max_length=80),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
