# Generated by Django 5.0.6 on 2024-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0004_alter_entidad_bancocup_alter_entidad_cuentacl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='valormag',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor del Margen Comercial CUP'),
        ),
    ]
