# Generated by Django 5.0.6 on 2024-05-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0005_alter_categoria_valormag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=250, verbose_name='Código')),
                ('descrip', models.CharField(max_length=250, verbose_name='Descripción')),
                ('um', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('precioCUP', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Precio CUP')),
                ('precioCL', models.DecimalField(decimal_places=5, max_digits=18, verbose_name='Precio CL')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Artículo Activado/Artículo no Activado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_app.categoria')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
