# Generated by Django 5.0.6 on 2024-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0006_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
